from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Role', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(choices=[('admin', 'Администратор'), ('operator', 'Оператор'), ('dispatcher', 'Маневровый диспетчер')], max_length=32, unique=True, verbose_name='Роль'))]),
        migrations.CreateModel(name='RailwayTrack', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=120, verbose_name='Название')), ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер')), ('type', models.CharField(default='приемо-отправочный', max_length=80, verbose_name='Тип')), ('length', models.PositiveIntegerField(default=850, verbose_name='Длина, м')), ('capacity', models.PositiveIntegerField(default=55, verbose_name='Вместимость вагонов')), ('description', models.TextField(blank=True, verbose_name='Описание')), ('is_active', models.BooleanField(default=True, verbose_name='Активен'))], options={'ordering': ['number']}),
        migrations.CreateModel(name='UserProfile', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rail.role')), ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='TrackSection', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=120, verbose_name='Участок')), ('position_start', models.PositiveIntegerField(default=0, verbose_name='Начало, м')), ('position_end', models.PositiveIntegerField(default=100, verbose_name='Конец, м')), ('max_wagons', models.PositiveIntegerField(default=10, verbose_name='Максимум вагонов')), ('coordinates_x', models.PositiveIntegerField(default=0)), ('coordinates_y', models.PositiveIntegerField(default=0)), ('is_occupied', models.BooleanField(default=False, verbose_name='Занят')), ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='rail.railwaytrack'))], options={'ordering': ['track__number', 'position_start']}),
        migrations.CreateModel(name='Train', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('train_number', models.CharField(max_length=40, unique=True, verbose_name='Номер состава')), ('arrival_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата прибытия')), ('departure_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправления')), ('status', models.CharField(choices=[('arrived', 'Прибыл'), ('placed', 'Размещен'), ('processing', 'В обработке'), ('ready_to_depart', 'Готов к отправлению'), ('departed', 'Отправлен')], default='arrived', max_length=32, verbose_name='Статус')), ('cargo_type', models.CharField(blank=True, max_length=120, verbose_name='Тип груза')), ('comment', models.TextField(blank=True, verbose_name='Комментарий')), ('is_archived', models.BooleanField(default=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ('current_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rail.tracksection')), ('current_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rail.railwaytrack'))], options={'ordering': ['-arrival_datetime']}),
        migrations.CreateModel(name='Wagon', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('wagon_number', models.CharField(max_length=40, unique=True, verbose_name='Номер вагона')), ('cargo_type', models.CharField(blank=True, max_length=120, verbose_name='Тип груза')), ('cargo_description', models.TextField(blank=True, verbose_name='Описание груза')), ('status', models.CharField(choices=[('loaded', 'Груженый'), ('unloaded', 'Порожний'), ('waiting_unload', 'Ожидает выгрузки'), ('unloading', 'Выгружается'), ('maintenance', 'Ремонт'), ('ready_to_depart', 'Готов к отправлению'), ('departed', 'Отправлен')], default='waiting_unload', max_length=32, verbose_name='Статус')), ('arrival_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата прибытия')), ('departure_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправления')), ('comment', models.TextField(blank=True, verbose_name='Комментарий')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('current_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rail.tracksection')), ('current_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rail.railwaytrack')), ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wagons', to='rail.train'))], options={'ordering': ['wagon_number']}),
        migrations.CreateModel(name='Document', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('file', models.FileField(upload_to='documents/')), ('document_type', models.CharField(default='накладная', max_length=80, verbose_name='Тип документа')), ('uploaded_at', models.DateTimeField(auto_now_add=True)), ('ocr_status', models.CharField(choices=[('uploaded', 'Загружен'), ('processing', 'Обрабатывается'), ('recognized', 'Распознан'), ('error', 'Ошибка'), ('confirmed', 'Подтвержден')], default='uploaded', max_length=24)), ('recognized_text', models.TextField(blank=True)), ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rail.train')), ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))], options={'ordering': ['-uploaded_at']}),
        migrations.CreateModel(name='MovementHistory', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('object_type', models.CharField(choices=[('train', 'Состав'), ('wagon', 'Вагон')], max_length=16)), ('moved_at', models.DateTimeField(auto_now_add=True)), ('comment', models.TextField(blank=True)), ('from_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rail.tracksection')), ('from_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rail.railwaytrack')), ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ('to_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rail.tracksection')), ('to_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rail.railwaytrack')), ('train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rail.train')), ('wagon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rail.wagon'))], options={'ordering': ['-moved_at']}),
        migrations.CreateModel(name='Notification', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('title', models.CharField(max_length=160)), ('message', models.TextField()), ('type', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('success', 'Успех')], default='info', max_length=16)), ('is_read', models.BooleanField(default=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL))], options={'ordering': ['-created_at']}),
        migrations.CreateModel(name='OCRResult', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('train_number', models.CharField(blank=True, max_length=40)), ('wagon_count', models.PositiveIntegerField(blank=True, null=True)), ('cargo_type', models.CharField(blank=True, max_length=120)), ('arrival_date', models.DateField(blank=True, null=True)), ('raw_text', models.TextField(blank=True)), ('confidence', models.PositiveIntegerField(default=70)), ('confirmed_at', models.DateTimeField(blank=True, null=True)), ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='rail.document'))]),
        migrations.CreateModel(name='OperationLog', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('action', models.CharField(max_length=80)), ('object_type', models.CharField(blank=True, max_length=80)), ('object_id', models.PositiveIntegerField(blank=True, null=True)), ('description', models.TextField(blank=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))], options={'ordering': ['-created_at']}),
    ]
